name: Trigger Terraform Cloud Run via API

on:
  push:
    branches:
      - main

jobs:
  trigger-tfc-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create and Upload Configuration Version
        run: |
          echo "Creating configuration version..."

          # Step 1: Create config version
          RESPONSE=$(curl --silent --show-error \
            --header "Authorization: Bearer ${{ secrets.TFC_TOKEN }}" \
            --header "Content-Type: application/vnd.api+json" \
            --request POST \
            --data '{
              "data": {
                "type": "configuration-versions",
                "attributes": {
                  "auto-queue-runs": false
                }
              }
            }' \
            https://app.terraform.io/api/v2/workspaces/${{ secrets.TFC_WORKSPACE_ID }}/configuration-versions)

          CONFIG_UPLOAD_URL=$(echo "$RESPONSE" | jq -r .data.attributes."upload-url")
          CONFIG_ID=$(echo "$RESPONSE" | jq -r .data.id)

          echo "Config upload URL: $CONFIG_UPLOAD_URL"
          echo "Config ID: $CONFIG_ID"

          # Step 2: Archive terraform code
          tar -czf config.tar.gz .

          # Step 3: Upload archive
          curl --request PUT \
            --header "Content-Type: application/octet-stream" \
            --data-binary @config.tar.gz \
            "$CONFIG_UPLOAD_URL"

          # Step 4: Trigger run using the uploaded config version
          echo "Triggering run..."

          RUN_RESPONSE=$(curl --silent --show-error \
            --header "Authorization: Bearer ${{ secrets.TFC_TOKEN }}" \
            --header "Content-Type: application/vnd.api+json" \
            --request POST \
            --data '{
              "data": {
                "attributes": {
                  "message": "Triggered by GitHub Actions"
                },
                "type": "run",
                "relationships": {
                  "workspace": {
                    "data": {
                      "type": "workspaces",
                      "id": "'$TFC_WORKSPACE_ID'"
                    }
                  },
                  "configuration-version": {
                    "data": {
                      "type": "configuration-versions",
                      "id": "'$CONFIG_ID'"
                    }
                  }
                }
              }
            }' \
            https://app.terraform.io/api/v2/runs)

          echo "Run triggered. Response:"
          echo "$RUN_RESPONSE"

        env:
          TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
          TFC_WORKSPACE_ID: ${{ secrets.TFC_WORKSPACE_ID }}
