name: Terraform CI

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    name: Trigger Terraform Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Trigger Terraform Cloud Run
        run: |
          curl \
            --request POST \
            --header "Authorization: Bearer ${{ secrets.TFC_TOKEN }}" \
            --header "Content-Type: application/vnd.api+json" \
            --data '{
              "data": {
                "attributes": {
                  "message": "Triggered by GitHub Actions"
                },
                "type":"run",
                "relationships": {
                  "workspace": {
                    "data": {
                      "type": "workspaces",
                      "id": "'"${{ secrets.TFC_WORKSPACE_ID }}"'"
                    }
                  }
                }
              }
            }' \
            https://app.terraform.io/api/v2/runs
