name: Trigger Terraform Cloud Run via API

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger-tfc-run:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Starting Terraform Cloud API run..."

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Configuration Version
        id: create_config
        run: |
          response=$(curl \
            --header "Authorization: Bearer ${{ secrets.TFC_TOKEN }}" \
            --header "Content-Type: application/vnd.api+json" \
            --request POST \
            --data '{
              "data": {
                "type":"configuration-versions",
                "attributes": {
                  "auto-queue-runs": false
                }
              }
            }' \
            https://app.terraform.io/api/v2/workspaces/${{ secrets.TFC_WORKSPACE_ID }}/configuration-versions)

          echo "$response"
          upload_url=$(echo "$response" | jq -r .data.attributes."upload-url")
          echo "upload_url=$upload_url" >> $GITHUB_ENV

      - name: Prepare Terraform Configuration
        run: |
          mkdir tf_package
          cp *.tf tf_package/
          cp terraform.yaml tf_package/ || true
          tar -czf config.tar.gz -C tf_package .

      - name: Upload Configuration to Terraform
        run: |
          curl \
            --request PUT \
            --header "Content-Type: application/octet-stream" \
            --data-binary @config.tar.gz \
            "${{ env.upload_url }}"

      - name: Trigger Run
        run: |
          curl \
            --header "Authorization: Bearer ${{ secrets.TFC_TOKEN }}" \
            --header "Content-Type: application/vnd.api+json" \
            --request POST \
            --data '{
              "data": {
                "attributes": {
                  "message": "Triggered from GitHub Actions"
                },
                "type": "runs",
                "relationships": {
                  "workspace": {
                    "data": {
                      "type": "workspaces",
                      "id": "'${{ secrets.TFC_WORKSPACE_ID }}'"
                    }
                  }
                }
              }
            }' \
            https://app.terraform.io/api/v2/runs
