name: Trigger Terraform Cloud

on:
  push:
    branches: [ main ]  # <- Must match the branch you're pushing to

jobs:
  trigger-terraform-cloud:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Terraform Cloud Run via API
        run: |
          curl --request POST \
            --header "Authorization: Bearer ${{ secrets.TFC_TOKEN }}" \
            --header "Content-Type: application/vnd.api+json" \
            --data '{
              "data": {
                "attributes": {
                  "message": "Triggered by GitHub Actions"
                },
                "type": "run",
                "relationships": {
                  "workspace": {
                    "data": {
                      "type": "workspaces",
                      "id": "'"${{ secrets.TFC_WORKSPACE_ID }}"'"
                    }
                  }
                }
              }
            }' \
            https://app.terraform.io/api/v2/runs
