name: Trigger Terraform Cloud Run via API

on:
  push:
    branches:
      - main

jobs:
  trigger-tfc-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Configuration Version
        id: create_config
        run: |
          RESPONSE=$(curl --silent --request POST \
            --header "Authorization: Bearer ${{ secrets.TFC_TOKEN }}" \
            --header "Content-Type: application/vnd.api+json" \
            --data '{
              "data": {
                "type": "configuration-versions",
                "attributes": {
                  "auto-queue-runs": false
                },
                "relationships": {
                  "workspace": {
                    "data": {
                      "type": "workspaces",
                      "id": "'"${{ secrets.TFC_WORKSPACE_ID }}"'"
                    }
                  }
                }
              }
            }' https://app.terraform.io/api/v2/workspaces/${{ secrets.TFC_WORKSPACE_ID }}/configuration-versions)

          echo "$RESPONSE" > response.json
          CONFIG_ID=$(jq -r '.data.id' response.json)
          UPLOAD_URL=$(jq -r '.data.attributes."upload-url"' response.json)

          echo "CONFIG_ID=$CONFIG_ID" >> $GITHUB_ENV
          echo "UPLOAD_URL=$UPLOAD_URL" >> $GITHUB_ENV

      - name: Create tar.gz of Terraform Code
        run: |
          tar -czf config.tar.gz .

      - name: Upload Configuration to Terraform
        run: |
          curl --request PUT \
            --header "Content-Type: application/octet-stream" \
            --data-binary @config.tar.gz \
            "$UPLOAD_URL"

      - name: Trigger Run
        run: |
          curl --request POST \
            --header "Authorization: Bearer ${{ secrets.TFC_TOKEN }}" \
            --header "Content-Type: application/vnd.api+json" \
            --data '{
              "data": {
                "attributes": {
                  "message": "Run triggered via GitHub Actions"
                },
                "type": "run",
                "relationships": {
                  "workspace": {
                    "data": {
                      "type": "workspaces",
                      "id": "'"${{ secrets.TFC_WORKSPACE_ID }}"'"
                    }
                  },
                  "configuration-version": {
                    "data": {
                      "type": "configuration-versions",
                      "id": "'"$CONFIG_ID"'"
                    }
                  }
                }
              }
            }' https://app.terraform.io/api/v2/runs
